"""Create all tables

Revision ID: 6e24fe41d7cb
Revises: 
Create Date: 2024-10-21 20:34:27.541589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e24fe41d7cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activacion',
        sa.Column('id_lote', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('usuario_activador', sa.String(length=100), nullable=False),
        sa.Column('fecha_activacion', sa.Date(), nullable=False),
        sa.Column('numero_archivos', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id_lote')
    )
    op.create_table('index_table',
        sa.Column('id_documento', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id_lote', sa.Integer(), nullable=False),
        sa.Column('titulo_documento', sa.String(length=255), nullable=False),
        sa.Column('ocr', sa.Boolean(), nullable=True),
        sa.Column('tipo_documento', sa.String(length=100), nullable=False),
        sa.Column('trasladado_descargados', sa.Boolean(), nullable=True),
        sa.Column('url_descargados', sa.String(length=255), nullable=True),
        sa.Column('usuario_dueno', sa.String(length=100), nullable=False),
        sa.Column('supervisado', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['id_lote'], ['activacion.id_lote'], ),
        sa.PrimaryKeyConstraint('id_documento')
    )
    op.create_table('documento',
        sa.Column('id_documento', sa.Integer(), nullable=False),
        sa.Column('id_lote', sa.Integer(), nullable=False),
        sa.Column('contenido', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['id_documento'], ['index_table.id_documento'], ),
        sa.ForeignKeyConstraint(['id_lote'], ['activacion.id_lote'], ),
        sa.PrimaryKeyConstraint('id_documento')
    )
    op.create_table('contratos',
        sa.Column('id_documento', sa.Integer(), nullable=False),
        sa.Column('id_lote', sa.Integer(), nullable=False),
        sa.Column('consecutivo_contrato', sa.String(length=100), nullable=False),
        sa.Column('programa_mitigacion', sa.String(length=255), nullable=False),
        sa.Column('json_contratos_info_general', sa.JSON(), nullable=False),
        sa.Column('json_contratos_clausulas', sa.JSON(), nullable=False),
        sa.Column('json_contratos_amparos', sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(['id_documento'], ['index_table.id_documento'], ),
        sa.ForeignKeyConstraint(['id_lote'], ['activacion.id_lote'], ),
        sa.PrimaryKeyConstraint('id_documento')
    )
    op.create_table('otrosi',
        sa.Column('id_documento', sa.Integer(), nullable=False),
        sa.Column('id_lote', sa.Integer(), nullable=False),
        sa.Column('numero_otrosi', sa.String(length=100), nullable=False),
        sa.Column('consecutivo_contrato', sa.String(length=100), nullable=False),
        sa.Column('json_otrosi_info_general', sa.JSON(), nullable=False),
        sa.Column('json_otrosi_modificaciones', sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(['id_documento'], ['index_table.id_documento'], ),
        sa.ForeignKeyConstraint(['id_lote'], ['activacion.id_lote'], ),
        sa.PrimaryKeyConstraint('id_documento')
    )
    op.create_table('poliza',
        sa.Column('id_documento', sa.Integer(), nullable=False),
        sa.Column('id_lote', sa.Integer(), nullable=False),
        sa.Column('numero_otrosi', sa.String(length=100), nullable=True),
        sa.Column('numero_poliza', sa.String(length=100), nullable=False),
        sa.Column('consecutivo_contrato', sa.String(length=100), nullable=False),
        sa.Column('json_poliza_info_general', sa.JSON(), nullable=False),
        sa.Column('json_poliza_amparos', sa.JSON(), nullable=False),
        sa.Column('hallazgos', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['id_documento'], ['index_table.id_documento'], ),
        sa.ForeignKeyConstraint(['id_lote'], ['activacion.id_lote'], ),
        sa.PrimaryKeyConstraint('id_documento')
    )
    op.create_table('documentos_generados',
        sa.Column('id_documento_generado', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id_lote', sa.Integer(), nullable=False),
        sa.Column('consecutivo_contrato', sa.String(length=100), nullable=False),
        sa.Column('titulo_documento_generado', sa.String(length=255), nullable=False),
        sa.Column('url_documento_generado', sa.String(length=255), nullable=False),
        sa.Column('json_total', sa.JSON(), nullable=False),
        sa.Column('enviado', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['id_lote'], ['activacion.id_lote'], ),
        sa.PrimaryKeyConstraint('id_documento_generado')
    )
    op.create_table('tabla_madre',
        sa.Column('consecutivo_contrato', sa.String(length=100), nullable=False),
        sa.Column('id_documento_contrato', sa.Integer(), nullable=False),
        sa.Column('id_documento_otrosi', postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column('id_documento_poliza', postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column('done', sa.Boolean(), nullable=True),
        sa.Column('query', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['id_documento_contrato'], ['contratos.id_documento'], ),
        sa.PrimaryKeyConstraint('consecutivo_contrato')
    )
    op.create_table('otrosi_tabla_madre',
        sa.Column('id_documento', sa.Integer(), nullable=False),
        sa.Column('consecutivo_contrato', sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(['consecutivo_contrato'], ['tabla_madre.consecutivo_contrato'], ),
        sa.ForeignKeyConstraint(['id_documento'], ['otrosi.id_documento'], ),
        sa.PrimaryKeyConstraint('id_documento', 'consecutivo_contrato')
    )
    op.create_table('poliza_tabla_madre',
        sa.Column('id_documento', sa.Integer(), nullable=False),
        sa.Column('consecutivo_contrato', sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(['consecutivo_contrato'], ['tabla_madre.consecutivo_contrato'], ),
        sa.ForeignKeyConstraint(['id_documento'], ['poliza.id_documento'], ),
        sa.PrimaryKeyConstraint('id_documento', 'consecutivo_contrato')
    )
    # Add the new chain_otrosi table
    op.create_table('chain_otrosi',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('output_prompt_extractor', sa.JSON(), nullable=True),
        sa.Column('output_prompt_estandarizador', sa.JSON(), nullable=True),
        sa.Column('tokens_input', sa.Integer(), nullable=True),
        sa.Column('tokens_output', sa.Integer(), nullable=True),
        sa.Column('total_tokens', sa.Integer(), nullable=True),
        sa.Column('otrosi_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['otrosi_id'], ['otrosi.id_documento'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chain_otrosi_id'), 'chain_otrosi', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chain_otrosi_id'), table_name='chain_otrosi')
    op.drop_table('chain_otrosi')
    op.drop_table('poliza_tabla_madre')
    op.drop_table('otrosi_tabla_madre')
    op.drop_table('tabla_madre')
    op.drop_table('documentos_generados')
    op.drop_table('poliza')
    op.drop_table('otrosi')
    op.drop_table('contratos')
    op.drop_table('documento')
    op.drop_table('index_table')
    op.drop_table('activacion')
    # ### end Alembic commands ###
