# alembic/versions/xxxxxxxx_create_tables.py
"""create tables

Revision ID: xxxxxxxx
Revises: 
Create Date: YYYY-MM-DD HH:MM:SS.SSSSSS

"""
from alembic import op
import sqlalchemy as sa


revision = 'xxxxxxxx'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activacion',
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('usuario_activador', sa.String(length=100), nullable=False),
    sa.Column('fecha_activacion', sa.Date(), nullable=False),
    sa.Column('numero_archivos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_lote')
    )
    # Create other tables similarly
    # For brevity, not all tables are created here
    # ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activacion')
    # Drop other tables similarly
    # ###
    pass
